.PHONY: all clean test build release lint fmt markdownlint nixie

build: target/debug/{{ package_name }}
release: target/release/{{ package_name }}

all: release

clean:
	cargo clean

test:
	RUSTFLAGS="-D warnings" cargo test

target/debug/{{ package_name }}:
	cargo build --bin {{ package_name }}

target/release/{{ package_name }}:
	cargo build --release --bin {{ package_name }}

lint:
	cargo clippy --all-targets --all-features -- -D warnings

fmt:
	cargo fmt --all
	mdformat-all

markdownlint:
	find . -name '*.md' -print0 | xargs -0 markdownlint

nixie:
	find . -name '*.md' -print0 | xargs -0 nixie
