#!/usr/bin/env -S uv run python
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""Generate ``typos.toml`` enforcing en-GB-oxendict (Oxford) spelling.

The ``en-gb`` locale in ``typos`` corrects American spellings to British
ones, but it prefers the ``-ise`` family and rejects Oxford ``-ize`` forms.
For each curated stem this script therefore emits:

- an identity entry accepting each Oxford ``-ize`` inflection that the
  locale would otherwise "correct" to ``-ise``, and
- an ``-ise`` to ``-ize`` correction for the same inflection, which the
  locale accepts silently.

Stems taking ``-yse`` (analyse, paralyse, catalyse) are deliberately
absent: Oxford retains ``-yse`` and the locale already enforces it.
Genuinely ``-ise``-only words (advise, revise, exercise, supervise, and so
on) are excluded from the stem list, so they remain accepted.

Examples
--------
Run from the repository root to rewrite ``typos.toml`` in place:

>>> # python3 scripts/generate_typos_config.py  # doctest: +SKIP

Verify the committed configuration instead of rewriting it:

>>> # python3 scripts/generate_typos_config.py --check  # doctest: +SKIP

The stem ``organ`` produces entries such as ``organised = "organized"``
and ``organized = "organized"`` for every suffix pair.
"""

import argparse
import difflib
import sys
import tomllib
from pathlib import Path

#: Word stems that take Oxford ``-ize``; each stem is the word up to but
#: not including the ``-ise``/``-ize`` suffix. Curated for vocabulary
#: plausible in software documentation; extend as new words appear.
STEMS = (
    "anonym",
    "apolog",
    "author",
    "canonical",
    "capital",
    "categor",
    "central",
    "character",
    "civil",
    "colon",
    "conceptual",
    "container",
    "contextual",
    "critic",
    "custom",
    "decentral",
    "denormal",
    "deserial",
    "destabil",
    "emphas",
    "energ",
    "equal",
    "external",
    "factor",
    "familiar",
    "final",
    "formal",
    "fossil",
    "general",
    "global",
    "harmon",
    "hypothes",
    "ideal",
    "initial",
    "internal",
    "international",
    "item",
    "jeopard",
    "legitim",
    "linear",
    "local",
    "material",
    "maxim",
    "mechan",
    "memor",
    "miniatur",
    "minim",
    "mobil",
    "modern",
    "modular",
    "monet",
    "neutral",
    "normal",
    "operational",
    "optim",
    "organ",
    "parameter",
    "parametr",
    "penal",
    "personal",
    "plural",
    "priorit",
    "public",
    "quant",
    "random",
    "rational",
    "real",
    "recogn",
    "regular",
    "reinitial",
    "reorgan",
    "sanit",
    "scrutin",
    "serial",
    "singular",
    "special",
    "stabil",
    "standard",
    "styl",
    "subsid",
    "summar",
    "symbol",
    "synchron",
    "synthes",
    "systemat",
    "theor",
    "token",
    "trivial",
    "unauthor",
    "uncategor",
    "uninitial",
    "unoptim",
    "unrecogn",
    "unsynchron",
    "util",
    "vector",
    "virtual",
    "visual",
)

#: Words accepted verbatim: suffix fragments quoted in prose and
#: hyphenated prefixes split by the tokenizer.
EXTRA_ACCEPTED_WORDS = (
    "yse",  # the "-yse" suffix quoted in spelling guidance
    "mis",  # hyphenated prefix, as in "mis-applied"
)

#: (British ``-ise`` inflection, Oxford ``-ize`` inflection) suffix pairs.
SUFFIX_PAIRS = (
    ("ise", "ize"),
    ("ises", "izes"),
    ("ised", "ized"),
    ("ising", "izing"),
    ("iser", "izer"),
    ("isers", "izers"),
    ("isable", "izable"),
    ("isation", "ization"),
    ("isations", "izations"),
)

HEADER = """\
# typos configuration enforcing en-GB-oxendict (Oxford spelling).
#
# Generated by scripts/generate_typos_config.py; regenerate rather than
# editing entries by hand:
#
#     python3 scripts/generate_typos_config.py
#
# The en-gb locale corrects American spellings (color -> colour,
# behavior -> behaviour, analyzed -> analysed) but prefers -ise over the
# Oxford -ize. The extend-words table below restores Oxford spelling:
# identity entries accept -ize inflections, and -ise entries are
# corrected to -ize.

[files]
extend-exclude = [
    ".git",
    ".venv",
    "target",
    "node_modules",
    "Cargo.lock",
]

[default]
locale = "en-gb"
extend-ignore-re = [
    # Inline code spans and fenced code blocks quote APIs and identifiers,
    # which keep their upstream spelling (for example `color`, `flavor`).
    '`[^`\\n]+`',
    '(?s)```.*?```',
    # Tool names that keep their upstream spelling even when they appear
    # outside code spans.
    'rust-analyzer',
    # External citation titles keep their published spelling.
    'Center \\| Microsoft Learn',
]

[default.extend-words]
"""


def render_config() -> str:
    """Render the full ``typos.toml`` document as a string.

    Returns
    -------
    str
        The configuration text, ending with a trailing newline.

    Examples
    --------
    >>> 'organised = "organized"' in render_config()
    True
    """
    lines = [HEADER.rstrip("\n")]
    lines.extend(f'{word} = "{word}"' for word in EXTRA_ACCEPTED_WORDS)
    lines.extend(
        entry
        for stem in sorted(STEMS)
        for ise, ize in SUFFIX_PAIRS
        for entry in (
            f'{stem}{ise} = "{stem}{ize}"',
            f'{stem}{ize} = "{stem}{ize}"',
        )
    )
    return "\n".join(lines) + "\n"


def default_output() -> Path:
    """Return the default ``typos.toml`` path in the repository root.

    Returns
    -------
    Path
        ``typos.toml`` one level above this script's directory.

    Examples
    --------
    >>> default_output().name
    'typos.toml'
    """
    return Path(__file__).resolve().parent.parent / "typos.toml"


def check(output: Path | None = None) -> int:
    """Verify the rendered configuration and the committed file.

    Parses the rendered document with :mod:`tomllib`, which fails fast on
    duplicate ``extend-words`` keys, asserts the exact entry count, and
    diffs the committed ``typos.toml`` against the generator output.

    Parameters
    ----------
    output : Path or None
        Committed configuration file to compare. Defaults to
        ``typos.toml`` in the repository root, resolved relative to this
        script.

    Returns
    -------
    int
        Zero when the checks pass; one on any parse failure, entry-count
        mismatch, or drift between the committed file and the generator.

    Examples
    --------
    >>> check()  # doctest: +SKIP
    0
    """
    if output is None:
        output = default_output()
    rendered = render_config()
    try:
        parsed = tomllib.loads(rendered)
    except tomllib.TOMLDecodeError as error:
        print(f"generated typos.toml is not valid TOML: {error}", file=sys.stderr)
        return 1
    extend_words = parsed["default"]["extend-words"]
    expected = len(EXTRA_ACCEPTED_WORDS) + 2 * len(STEMS) * len(SUFFIX_PAIRS)
    if len(extend_words) != expected:
        print(
            "generated extend-words table has "
            f"{len(extend_words)} entries; expected {expected} "
            "(a stem/suffix combination or accepted word collides)",
            file=sys.stderr,
        )
        return 1
    if not output.exists():
        print(f"missing committed configuration: {output}", file=sys.stderr)
        return 1
    committed = output.read_text(encoding="utf-8")
    if committed != rendered:
        diff = difflib.unified_diff(
            committed.splitlines(keepends=True),
            rendered.splitlines(keepends=True),
            fromfile=str(output),
            tofile="generated",
        )
        sys.stderr.writelines(diff)
        print(
            "typos.toml drifted from the generator; regenerate with "
            "python3 scripts/generate_typos_config.py",
            file=sys.stderr,
        )
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    """Write the rendered configuration, or verify it with ``--check``.

    Parameters
    ----------
    argv : list of str or None
        Command-line arguments. Defaults to ``sys.argv[1:]``.

    Returns
    -------
    int
        Process exit status: zero on success, one on a failed check.

    Examples
    --------
    >>> main([])  # doctest: +SKIP
    0
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed typos.toml instead of rewriting it",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="destination file (defaults to typos.toml in the repository root)",
    )
    arguments = parser.parse_args(argv)
    if arguments.check:
        return check(arguments.output)
    output = arguments.output if arguments.output is not None else default_output()
    output.write_text(render_config(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
